### ISSUE TITLE
Error 429 the headers collection is Empty

### ISSUE THREAD

**Issue by pentiumii400mhz** [JohnnyCrazy/SpotifyAPI-NET#113]
When I'm getting a Error 429 the headers is Empty!

![image](https://cloud.githubusercontent.com/assets/21958884/18243371/2029d278-735b-11e6-9b0b-37b4f38e52ca.png)

![image](https://cloud.githubusercontent.com/assets/21958884/18243377/27fa88f8-735b-11e6-80a2-9f6d089b2404.png)

![image](https://cloud.githubusercontent.com/assets/21958884/18243387/2d1ae544-735b-11e6-968e-cfdd33fbfc3b.png)

**Comment by JohnnyCrazy** [comment]
AFAIK this can't be solved with the current `WebClient` Implementation. When the status code is not `2XX`, the client will raise and the response headers can't be retrieved.

However, I already did most of the rewrite to .NET Core, which will use `HttpClient`. It should work then, so it's gonna be fixed in 3.0

**Comment by JohnnyCrazy** [comment]
Headers should be visible in all cases in [2.14.0](https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/2.14.0)
