### ISSUE TITLE
Use with Xamarin.Android

### ISSUE THREAD

**Issue by voltagex** [JohnnyCrazy/SpotifyAPI-NET#117]
It looks like I can't use this library with Xamarin.Android, including it causes the Xamarin build targets to break: 
```
error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
```

Edit, some time later:

Well that was "fun". The first issues are GetAlbumArtAsync and GetAlbumArt in Local/Models/Track.cs. I should probably just ifdef the whole Local API out as it won't be needed on a mobile device.

The second issue is more difficult. System.Web will never be supported in Xamarin, so it looks like I'd have to reimplement SpotifyWebClient / IClient to use something like HttpClient. If this were my library, I'd probably just rewrite SpotifyWebClient to use HttpClient (removing the dependency on System.Web), that way you could turn SpotifyAPI into a portable / .NET standard library.

**Comment by JohnnyCrazy** [comment]
Hi, we are currently discussing the port to `HTTPClient` in #104 . I don't know when I will have time to do the major changes, but I guess it shouldn't take too long.

Relating the local-API: It's also planned to convert this to .NET-Core standards since the local api works on any platform (win, linux, osx)

I will close this in favor of #104
