### ISSUE TITLE
Can't get the application to check if track is changed.

### ISSUE THREAD

**Issue by bicobajas** [JohnnyCrazy/SpotifyAPI-NET#132]
` public void trackChange(object sender, TrackChangeEventArgs e)
        {
            MessageBox.Show("Track Changed");
        }
 if (_spotify.GetStatus().Running = true)
                    {
                        trackChange();
                    }
`
I'm not very savy at coding but i hope someone could give me a hand here, since i get an error when i try to call the event.

Severity	Code	Description	Project	File	Line
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'sender'

**Comment by jipjan** [comment]
Do you have a method trackChange which doesn't have any parameters? Otherwise you are trying to call the same method you are in without parameters. Even if you add the parameters (like trackChange(sender, e)) you would create an infinite loop.

So the question is, what are you trying to do when you change track. By the way, you dont need to check if Spotify is running when the event triggers, you know at this point it must be running, otherwise the call wouldn't have been made.

**Comment by bicobajas** [comment]
My idea is to have a listbox with the songs that have played, so that when track changes it adds the new track to the list box, but i get an error every time i try this, i could send the whole code to you if you want to take a look for me?

**Comment by jipjan** [comment]
Sure!
If I have some time I can also create an example solution for you based on your idea.

**Comment by bicobajas** [comment]
Sent, All i want is to get the trackchanged event to work so it can execute some code for me upon event trigger.

**Comment by jipjan** [comment]
The problem is solved, this can be closed.
