### ISSUE TITLE
Getting a System.IO.FileLoadException when calling getStatus()

### ISSUE THREAD

**Issue by sliptrix** [JohnnyCrazy/SpotifyAPI-NET#228]
This is observed in the SpotifyLocalApi object
![screenshot 54](https://user-images.githubusercontent.com/37605842/37692956-67f2332e-2c79-11e8-8102-962bce7a5f2f.png)

**Comment by aleab** [comment]
The exception is pretty clear and the problem is entirely on your end. Your exe couldn't find any matching Newtonsoft.Json assembly in the filepath.
Download the latest Nuget package and make sure its manifest definition matches the one declared in your app.config.
In particular, your app is expecting an assembly with major version 10.
