### ISSUE TITLE
Previous() doesn't work always!

### ISSUE THREAD

**Issue by xTheChosen0ne** [JohnnyCrazy/SpotifyAPI-NET#231]
Unfortunately, like the title describes, the Previous() method doesn't work always. It works when your usual in your Program, but not when you're in a fullscreen (like a game). It doesn't matter which program (or game) it is, this problem comes always when you're in fullscreen.

So I reproduced your API-Code-Snippet of the Previous()-Method into my usual Code to understand how you work in this case. I think the problem is, that you can't use the "VK_MEDIA_NEXT_TRACK"-Key (and the other Media-Track-Keys too I think) when you're in fullscreen. But I **know** that it wasn't always like that. It should be a Windows Bug from one of the latest updates, or maybe it is even intended.

Maybe you can do a workaround and make the Previous-Method possible without simulating the Medie-Next-Track-Key?

Greets

**Comment by aleab** [comment]
Hi @xTheChosen0ne!
While waiting for @JohnnyCrazy's response, I think you can try using the [`PostMessage`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644944.aspx) function from the Windows APIs instead of using media keys.
Specifically, you wanna do something like the following:
```c#
[return: MarshalAs(UnmanagedType.Bool)]
[DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
private static extern bool PostMessage(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam);

private const uint WM_APPCOMMAND = 0x0319;
private const long cmdNextTrack = 0x000B0000L;
private const long cmdPreviousTrack = 0x000C0000L;

private IntPtr spotifyHWnd;  // This is a handle to Spotify's main window

public void NextTrack()
{
    PostMessage(spotifyHWnd, WM_APPCOMMAND, IntPtr.Zero, (IntPtr)cmdNextTrack);
}

public void PreviousTrack()
{
    PostMessage(spotifyHWnd, WM_APPCOMMAND, IntPtr.Zero, (IntPtr)cmdPreviousTrack);
}
```

The above code is pretty similiar to what I'm using in my application and it works fine with fullscreen videogames.

Provided you first found the right Spotify's `Process p`, you can simply do `p.MainWindowHandle` to get the handle of its main window. This, however, will not work if Spotify is minimized to the tray; in that case you should use something like [this](https://github.com/aleab/toastify/blob/0f01a34768cd990f658fcb7b45d4384e67284cd8/ToastifyAPI/Spotify.cs#L78-L98), where `uint pid = unchecked((uint)p.Id)`.

**Comment by xTheChosen0ne** [comment]
@aleab Awesome, thanks! Tried it, works perfect. @JohnnyCrazy You should think about override the Media-Key-Simulations with this solution.

For the other vb.net-Programmers, here:

```
<DllImport("user32.dll")>
    Private Shared Function PostMessage(ByVal hWnd As IntPtr, ByVal msg As UInteger, ByVal wParam As IntPtr, ByVal lParam As IntPtr) As Long
    End Function

    Private Sub spotifyPrev()
        Const WM_APPCOMMAND As UInteger = &H319
        Const cmdNextTrack As Long = &HC0000L
        Const cmdPreviousTrack As Long = &HC0000L

        Dim spotifyprozesse As Process() = Process.GetProcessesByName("spotify")

        Dim spotifyHWnd As IntPtr  'This is a handle to Spotify's main window
        For Each spotifyprozess In spotifyprozesse
            If spotifyprozess.MainWindowHandle.ToString <> "0" Then
                spotifyHWnd = spotifyprozess.MainWindowHandle
            End If
        Next

        PostMessage(spotifyHWnd, WM_APPCOMMAND, IntPtr.Zero, CType(cmdPreviousTrack, IntPtr))
    End Sub
```

**Comment by JohnnyCrazy** [comment]
Seems like a good idea, maybe we can even emulate more actions with this way.

I will try to find some time implementing it, toastifys solution seems very good already. If someone else wants to go for it, just let me know.
