### ISSUE TITLE
How to make browser forget Spotify login?

### ISSUE THREAD

**Issue by CaptainMorgs** [JohnnyCrazy/SpotifyAPI-NET#238]
I am using ImplicitGrantAuth for authentication and I can't seem to force my browser to forget my Spotify login to allow me to try other Spotify accounts. I've tried clearing Firefox's history including active logins. Any help would really be appreciated I have a demo Friday and I need to be able to demo multiple accounts!

Edit: show_dialog appears to be my solution but I don't know how to specify this with the WebAPIFactory

**Comment by CaptainMorgs** [comment]
Solved it. Just needed to add "&show_dialog=true" as an argument to the WebAPIFactory

**Comment by aleab** [comment]
The first error message in Unity makes me think the internal http server timed out before receiving the response from the browser. You should try to increase the timeout.

You may also need to create your own WebAPIFactory that uses the `ShowDialog` property of `ImplicitGrantAuth`, since it doesn't seem to be possible with the current one.

**Comment by JohnnyCrazy** [comment]
Fixed by #239
