### ISSUE TITLE
[IMPORTANT] SpotifyLocalAPI not working

### ISSUE THREAD

**Issue by StepIg** [JohnnyCrazy/SpotifyAPI-NET#254]
With the last version, has worked one time, but no more. Play and pause doesn't work.

**Comment by StepIg** [comment]
Also on Example project, once connected to Spotify, doesn't receive Title, Artist, Album.
Previous and Skip buttons are working ok.
Spotify version 1.0.85.257.gOf8531bd

**Comment by hng0vrboy** [comment]
I can confirm that with the latest Spotify release and the latest API release, Play does not work anymore.

**Comment by phICE9** [comment]
I am also having problems with play or PlayUrl function

**Comment by sakertooth** [comment]
I'm having the same issue

**Comment by TippeTiTop** [comment]
same here
play, pause etc. doesn't work
yesterday i was able to fix it with the solution provided in #253
[Spotify version 1.0.85.257.gOf8531bd]

**Comment by Inzaniity** [comment]
LocalAPI Seems to broken. GetStatus() reuturns always Null. It hast been down since yesterday evening.

**Comment by renatopda8** [comment]
The OAuth key request to "http://open.spotify.com/token" is always returning an invalid token.

**Comment by RobertRoxenhall** [comment]
Yeah same issue here. Can we get an updated version again? :)

**Comment by JohnnyCrazy** [comment]
Uhhhh, gimme some minutes here, seems like they disabled the OAuth Token, which maybe means local API is dead. Will report back once I found out more...

**Comment by JohnnyCrazy** [comment]
Well, it seems like they either disabled the Token generation, or sending a `User-Agent` with the spotify version is not enough anymore. Independently, there is nothing we can do atm because it's an unofficial API and they can just introduce some secret header field which we could not find in ages.

Also, with their changes to the WebAPI which now also allows managing devices & streaming, it's reasonable that they disabled the local API. It was mainly used for the old web-player which is now completely based on the new WebAPI.

There is not much we can do at the current state...

**Comment by RobertRoxenhall** [comment]
No... just no. I have this (well had actually) working solution and we're going live tomorrow morning and then I need to be able to control Spotify from a tablet (among other things).

Well, guess I'll have to rebuild it to use the web-api and control the playback that way. Guess I should see it from the bright side. Now atleast I have the entire night to fix it. Had it happened tomorrow I'd be ******.

Thank you for the quick update! (I was hoping someone at Spotify accidentally uploaded a test version of their token generator and would fix it shortly)

**Comment by StepIg** [comment]
Why skip and previous still working?

**Comment by JohnnyCrazy** [comment]
@StepIg Because they emulate media keys, no spotify api involved

**Comment by hng0vrboy** [comment]
So by using the web api, we can control and play songs on the spotify instance running on a windows machine?  (So basically the same thing that the LocalAPI did when we called the play method?)

**Comment by rollersteaam** [comment]
So my jaw just dropped after spending about 5 hours finding this solution to the problem and actually hearing music go through my headphones when I clicked my program's play button.

Assuming we can no longer use the local API (I hope this is temporary), I've made a new class that implements the same interface as my class that used the SpotifyLocalAPI. This new class uses SpotifyWebAPI.

On initialisation we need to request authentication from the Spotify API. Normally this would be hard or tedious to do, except @JohnnyCrazy has already implemented a way in his SpotifyWebAPI example inside the 'Example' folder in this repository.

This is a small adaptation of his example into an async function that you can basically just copy and paste into your project for initialisation of your new web API class.

```c#
async void ResolveAuth()
{
    WebAPIFactory webApiFactory = new WebAPIFactory(
        "http://localhost",
        8000,
        "26d287105e31491889f3cd293d85bfea",
        Scope.UserReadPrivate | Scope.UserReadEmail | Scope.PlaylistReadPrivate | Scope.UserLibraryRead |
        Scope.UserReadPrivate | Scope.UserFollowRead | Scope.UserReadBirthdate | Scope.UserTopRead | Scope.PlaylistReadCollaborative |
        Scope.UserReadRecentlyPlayed | Scope.UserReadPlaybackState | Scope.UserModifyPlaybackState,
        new SpotifyAPI.ProxyConfig());
 
    try
    {
        spotify = await webApiFactory.GetWebApi();
    }
    catch (Exception ex)
    {
        throw;
    }
 
    if (spotify == null)
        return;
}
```

Now for when we want to play a song, we have to use the functions in SpotifyWebAPI. Intellisense will be able to show you a good amount of information, but for playing a specific URI, here is an example.

```c#
        public void Play()
        {
            // Spotify ResumePlayback has a huge amount of parameters.

            // By using "uris: " and defining a new list of strings, we are specifying that we want to give only the
            // parameter "uris" input, and nothing else (because all parameters here are optional.)

            // the parameter uris is simple, it is a list of song uri's you want to play.

            // Offset has to be passed in here (although I pass in its default optional parameter value) as
            // the compiler won't be able to differentiate between the two different overloads for the method ResumePlayback.

            // For many functions in the web API, they will want 'contexts' and 'device ids'. These are basically all optional
            // so adapting these functions to replace your local API is probably doable.
            spotify.ResumePlayback(uris: new List<string> { "spotify:track:0cWPe8mPRyLMxxe94eRVzs" }, offset: "");
        }
```

If you read the comments you'll understand that I tried to explain some of the web API's jargon that you may have not read up on because you've relied on the local API for a while, so to follow up on my comments, here is an example of how to PAUSE playback, just to show how easy it is.

```c#
        public void Pause()
        {
            spotify.PausePlayback();
        }
```

But intellisense shows you can also pass in a device ID string. Completely optional, as shown in the method's summary.

So what if I want to just resume playback instead of play a new song?

```c#

        public void Play()
        {
            // Again, we have to state offset's parameter value so it differentiates between the two overloads of the method.
            // Just pass in an empty string, as that is its default optional parameter value.
            spotify.ResumePlayback(offset: "");
        }
```

**Comment by JohnnyCrazy** [comment]
Nice writeup @rollersteaam 👍 

2 notes:
* `spotify = await webApiFactory.GetWebApi();` will get you a ready-to-use OAuth token, but sadly it's only valid for 30 minutes, and you cant refresh it. There are some alternatives [here](https://johnnycrazy.github.io/SpotifyAPI-NET/SpotifyWebAPI/auth/#autorizationcodeauth)
* I don't think it's temporary, this would be weird for spotify since they, most of the time, are good at deploying stuff. But let's see 😅

**Comment by StepIg** [comment]
Then, local API is dead like we know it yesterday?

**Comment by Gruhlum** [comment]
@rollersteaam I tried PausePlayback() and ResumePlayback() but both gave me error "403 - Not available for the current user"
I have Scope.UserReadPlaybackState and Scope.UserModifyPlaybackState.

And shouldn't the offset for: 
`spotify.ResumePlayback(offset: ""); `
be an int and not string?

**Comment by rollersteaam** [comment]
@Gruhlum It's probably more coherent to state offset as 0 instead of as an empty string, but because both work I'm assuming it treats an empty string as having no offset anyway. I'm not sure how a string could define some form of offset but who knows

As for your problem, I didn't have the issue and I have Spotify premium, so it's possible, although it wouldn't make much sense since web players for Spotify should allow free users to still interact and play specific tracks. However, IIRC from the free version of Spotify on mobile, you cannot play specific tracks and are forced to play through "shuffle play," meaning if your device ID links to a mobile I suppose it's not going to let you. Again, why would it cause that issue on PausePlayback() though?

**Comment by h-philip** [comment]
@Gruhlum 
https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/ and https://developer.spotify.com/documentation/web-api/reference/player/pause-a-users-playback/ 

> If the user making the request is non-premium, a 403 FORBIDDEN response code will be returned.

**Comment by StepIg** [comment]
With permium all continues working?

**Comment by rollersteaam** [comment]
@Gruhlum While @h-philip has showed the reason why it won't work for you, I recently just had an issue with resuming playback and it was because offset was set to 0 instead of an empty string. When I changed it back to an empty string it allowed me to resume playback. @JohnnyCrazy This is a potential bug I think?

If that doc is definitely correct and isn't out of date, then forcing users to be premium is really, REALLY annoying. That's actually terrible. Do you think they disabled the local API just to force users to pay up?

**Comment by h-philip** [comment]
@rollersteaam Do you mean this #249?

**Comment by Gruhlum** [comment]
@h-philip 
Yes I have just found it myself. That's a real bummer looks like I am screwed now :(

**Comment by JohnnyCrazy** [comment]
> @Gruhlum While @h-philip has showed the reason why it won't work for you, I recently just had an issue with resuming playback and it was because offset was set to 0 instead of an empty string. When I changed it back to an empty string it allowed me to resume playback. @JohnnyCrazy This is a potential bug I think?

Please have a look at the docs before bug hunting: [Resume Playback](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/)

> Optional. Indicates from where in the context playback should start. Only available when context_uri corresponds to an album or playlist object, or when the uris parameter is used.“position” is zero based and can’t be negative. Example: "offset": {"position": 5}“uri” is a string representing the uri of the item to start at. Example: "offset": {"uri": "spotify:track:1301WleyT98MSxVHPZCA6M"}

**Comment by StepIg** [comment]
@rollersteaam 
// It should be noted, "http://localhost:8000" must be whitelisted in your dashboard after getting your own client key

i cant find the place to do that. Can you give some help?

**Comment by StepIg** [comment]
@rollersteaam 
  ```
 public void Pause()
        {
            spotify.PausePlayback();
        }
```
doesn't work for me on no-premium account.
and after call `spotify = await webApiFactory.GetWebApi();`
visual studio becomes practically frozen

**Comment by rollersteaam** [comment]
@StepIg Yeah unfortunately if the user making the request is no-premium, they won't fulfill it. I guess that's Spotify's own right, although I find it particularly scummy. Hopefully someone can discover a workaround.

For your frozen issue, calling that function will cause your app to hang until authentication is received or the request times out.

On call, your browser should open up and request for you to authenticate the app's access to your account. You will get an "Invalid URI redirect" message if you did not specify "http://localhost:8000" in your whitelisted addresses in your client dashboard, although if you did not supply your own client ID then you won't have this problem (because it will use JohnnyCrazy's client ID).

Alternatively, you can create a new Task like this:

```c#
void ResolveAuth() {
/// bla bla bla enter all the previous constructor code here
/// ...
            Task task = Task.Factory.StartNew(() =>
            {
                try
                {
                    // Since GetWebApi() is async, it returns a Task of return type WebAPIFactory, so we have to use ".Result" to access what the task has returned
                    spotify = webApiFactory.GetWebApi().Result;
                }
                catch (Exception ex)
                {
                    UpdateStatus($"Spotify service failed to load, Spotify music is unavailable. Exception: {ex.Message}");
                    throw;
                }
            });
}
```

If you didn't know, tasks create a new thread to handle a task so you can still do other things in your application without it freezing, but of course, you will have null references until you successfully get authentication, so it may not be worth using the Task system if you're expecting a reference to it no matter what.

Despite all that it's still possible because you're non-premium that it fails the authentication request immediately, but I think it would fail loudly and throw an exception if that were the case anyway. You would have to do a lot of null checks throughout your code as well, so I opted not to do this.

**Comment by StepIg** [comment]
@rollersteaam thanks for your help
but don't understand about  
> if you did not supply your own client ID then you won't have this problem (because it will use JohnnyCrazy's client ID).
How to do this?

**Comment by StepIg** [comment]
@rollersteaam Ok, working on premium account.
How to get time, track and artist for current track? Do you know?

**Comment by rollersteaam** [comment]
@Steplg On my phone atm so can't give large examples, but I posted the example of getting authentication further up, and with that spotifywebapi class you can find everything you'll need

Some basic things: GetPlayingTrack returns an object with variable ProgressMs, which is current track time in ms and inside is variable Item with durationms variable which is total track time in ms, as well as info for artist and album

**Comment by StepIg** [comment]
@rollersteaam 
ok, i will work on this. Thanks for your help
another question: is there any way to give spotify user and password without open the web page from spofity? that is without user intervention?

**Comment by h-philip** [comment]
https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/
Now we know, why they disabled it.

**Comment by StepIg** [comment]
Anyone can tell how to play a list from spotifyWebAPI?

**Comment by StepIg** [comment]
Someone can tell how to play a playlist with spotifyWebAPI, please?

**Comment by DanielGilbert** [comment]
Hm - so it looks like there are only two options left, if you need to know what's currently playing, and can't use the WebAPI (for whatever reasons):

1. Use open.spotify.com instead, and write a plugin for your favourite browser. This plugin could parse the DOM of the page. In fact, this would add some missing features the local API had. For instance, it always returned only one artist per song, even if there where multiple of them. The plugin could, e.g. via Websockets, connect to another client.

2. , and this is the more "awesome" approach: tinker around with the Spotify client itself. The client is, in fact, only Chromium + React, and the "spa"-files in the "Apps" folder are zipped files, which can be extracted and modified. There is a project for Rainmeter, which does exactly this: https://github.com/khanhas/Spicetify

So one could implement the "SpotifyWebHelper" as a pure WebSocket service (the aforementioned project has sth. like this). Although it requires tons and tons of tinkering (and a lot of time). BUT - it would be awesome. 😃

**Comment by StepIg** [comment]
@DanielGilbert Done all regarding what playing, elapsed time, etc...
Continue looking for play a list and also for make auth without show the browser

**Comment by JohnnyCrazy** [comment]
Okay, seems like it's official.

I will think about the future of the project. Probably it will focus on the web API. But I also like the idea of modifying the Spotify client is files to make a custom websocket helper. I will keep you updated

**Comment by StepIg** [comment]
Any idea about how to start play on spotify just after lunch spotify without user intevention?
after launch spotify, it starts stopped.
can connect using webAPI, but do not accept commands until play is pressed on spotify. After this, commands are accepted by spotify

**Comment by StepIg** [comment]
im working with the desktop client. but after your comment, is there a way to do not show destop or web spotify?

**Comment by JohnnyCrazy** [comment]
Okay, small plan for the future:

1. Remove the local API from this project and make sure we're getting the Web API .NET Standard ready. This was a highly requested feature and without the local API it should be done quite quick.

2. Remove the current Authentication stuff I build around spotify flows and extract it into a new project `SpotifyAPI.Butler` with a better API, and maybe even cross platform support.
I already had a look at [a cross platform webserver](https://github.com/unosquare/embedio) which looks promising. For the API, I thought of the following:
```c#
var butler = new SpotifyAPIButler(clientID, clientSecret, 3000);
// or for short lived tokens
var butler = new SpotifyAPIButler(clientID, 3000);

butler.OnAuthorizationCode+= OnAuthorizationCode; // (token, refreshToken)
butler.OnImplicitGrant += OnImplicitGrant; // (token)

butler.Start() // open users browser
var newToken = butler.RefreshToken(refreshToken) // maybe not even necessary
```

The API maybe will stay close to the old one, but definitely with better error handling and cross platform support.

And generally speaking: There is no secure way of using the Spotify Web API with long lasting tokens on the client side without a backend. The only option is: Every user has to create a developer application themselves and add the necessary `clientId` and `clientSecret` into the Desktop App. That's the only secure way.

**Comment by jscholes** [comment]
You're building an abstraction and my gut feeling is that someone should be able to gauge what it's for at a first glance of its name.  Unless I'm missing something the word butler doesn't relate to authorization in any way.  It's your library though - I only came here for discussion of the locally-hosted Spotify API which I used in one of my own Python-based projects ;)

**Comment by StepIg** [comment]
Now  SpotifyLocalAPI.RunSpotify() doesn't run on Windows 10.

**Comment by xTheChosen0ne** [comment]
Dat is jetzt natürlich nicht so geil 😆

**Comment by mmartain** [comment]
Hope this can get fixed. I am using the events from the local player. Any ideas for a workaround?

**Comment by StepIg** [comment]
@mmartain 
I've moved my code from events to timers taking needed info about tracks time, etc... from the webAPI. And all is ok.

**Comment by JohnnyCrazy** [comment]
There will be no fix. The local API will be removed with the next commit, the project will have the following structure:

* SpotifyAPI.Web (NuGet Package)
* SpotifyAPI.Web.Auth (NuGet Package)
* SpotifyAPI.Web.Example
* SpotifyAPI.Web.Tests

I'm currently reworking `SpotifyAPI.Web.Auth` with a better internal HTTP Server and an additional "auth-method", where users have to register their own spotify dev application. This will be the only "secure" authentication method.
