### ISSUE TITLE
Error: INVALID_CLIENT: Invalid redirect URI 

### ISSUE THREAD

**Issue by ratneshkumarcs** [JohnnyCrazy/SpotifyAPI-NET#271]
Hi,
when i trying to authenicate webAPI it gives me "INVALID_CLIENT: Invalid redirect URI" error.. I hace chnaged the clientID as well.. Also how to run local API ?

**Comment by jscholes** [comment]
You need to whitelist your redirect URI on the Spotify Developer dashboard for your app.  You then need to use the exact same URI when making your initial request to the Spotify accounts service - and I mean, exactly the same.  No trailing slashes, no HTTPS instead of HTTP.  If they don't match exactly, it will not work.

The local API is broken and can't be fixed.

**Comment by catara** [comment]
sorry to ask:

1. What are the exact steps? as i still get the same error
i've registered to the xxy client id in the Spotify dashboard, the redirect uri http://localhost:8000

https://accounts.spotify.com/authorize/?client_id=xxy%20&response_type=token&redirect_uri=http://localhost:8000&state=XSS&scope=playlist-read-private%20user-read-private%20user-read-email%20user-library-read%20user-follow-read%20user-read-birthdate%20user-top-read%20playlist-read-collaborative%20user-read-recently-played%20user-read-playback-state%20user-modify-playback-state&show_dialog=False

2. what do you mean by broken? couldn't understand from the other discussions
as my app stopped working (authentificating), is it something in 2.19? shall i go back to older versions?

3. what is local? i just want to query Spotify db, what other 'modes' allow me to do just that if not local

4. when if v3.0 avail by nuget?

**Comment by SimpleSandman** [comment]
**To answer the issue at hand:**
Have you tried using a different port number? I'm currently using `:4002` as shown in the [example code in this repo](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web.Example/Program.cs) and it worked for me. Make sure your in the Spotify Developer dashboard you make the proper changes for the redirect URI.

**For local API clarity:**
The local API refers to the app or program's API that is installed on a person's computer and as mentioned earlier, you cannot use the local API (version 2.19 or below of SpotifyAPI-NET) because it doesn't work anymore. Please use the latest version (above 3.0.0 of SpotifyAPI-NET).

**Implicit Grant Auth example:**
If you're having issues with the Authorization Code Flow, you can use JohnnyCrazy's example of Implicit Grant Auth [here](https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/283#issuecomment-419971022).

**Gist of the project >= version 3.0.0:**
This project starting at 3.0.0 now uses Spotify's Web API exclusively and if you want to authenticate a user, you need both packages. Please refer to both links in this comment for different ways of authenticating a user.

**Comment by JohnnyCrazy** [comment]
Please reopen if you still have issues or need some assistance.
