### ISSUE TITLE
SpotifyAPI.Web 3.0 Release

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#276]
Hey guys,

Changes in 3.0.0:
* .net standard support
* Seperated NuGet Packages for Core Client and Auth flows:
  * [SpotifyAPI.Web](https://www.nuget.org/packages/SpotifyAPI.Web/) - The API Client
  * [SpotifyAPI.Web.Auth](https://www.nuget.org/packages/SpotifyAPI.Web.Auth/) - The Auth flows
* Auth flows now use a really good webserver called [embedio](https://github.com/unosquare/embedio), no hacky internal solution
* Auth flows now can serve HTML/static files, so we could build a really good user experience
* Auth flows have a cleaner API and should be more stable
* Docs are not updated yet. But the API is very similar to the old one.

Till the docs are updated, feel free to ask stuff.

**Comment by Nensec** [comment]
Assuming I need the AuthorizationCodeAuth class to now do my auth, what do I fill in for the serverUri parameter?

**Comment by mmartain** [comment]
Are there any plans to integrate a way to have events again? This is specifically handy for recording programs that use this API.

**Comment by JohnnyCrazy** [comment]
@Nensec 

The `serverUri` parameter will be used as the listen address. In the example I'm using `http://localhost:4002`.

**Comment by JohnnyCrazy** [comment]
@mmartin

Not planned, since events don't make sense when using a REST API. We would need websocket support from spotify to cleanly implement it. But I guess you could roll your own polling and event trigger logic.

**Comment by mmartain** [comment]
@JohnnyCrazy you said u experimented with javascript hijacking. Are there any samples left using that method for the tinkerers?

**Comment by jasniec** [comment]
I've updated nuget package to 3.0.1 and i'm not sure, but i think i don't have Auth namespace http://prntscr.com/kmlg4g (i had this namespace used, but now it's lost).

I've tried to reinstall this nuget package, but it didn't help...
And this is nuget screenshot: http://prntscr.com/kmlh9o

Is this my fault or nuget problem?

**Comment by JohnnyCrazy** [comment]
@jasniec Did you actually read the top post? 😄

**Comment by jasniec** [comment]
Ok, sorry - i'm blind - that's what happens when you try to think in the middle of the night

**Comment by h-philip** [comment]
When I am doing the `auth.Start()` and `auth.OpenBrowser` in a client, is there a way to only give it the ClientId, and then let the server (within AuthReceived) add the SecretId before `ExchangeCode()`? When I am not setting the SecretId before `auth.Start(); auth.OpenBrowser()` I always have to enter everything manually, i think.
Or do I have to just give it anything as SecretId and then enter the right one before `ExchangeCode()`?

Maybe I am also doing something really wrong here :smile:

**Comment by JohnnyCrazy** [comment]
Good point @h-philip, maybe we should change the API to explicitly state if you want to let the user enter clientId and clientSecret. Currently, I'm just checking wether one of both values is empty or null.

Your proposed solution should work, but I guess we need to change it for some use-cases!

Out of curiosity, why dont you have the client secret when opening the browser? 😅

**Comment by h-philip** [comment]
Ich wollte eigentlich nur, dass ich nicht jedes mal die beiden Sachen selber eingeben muss. Also wenn der Client als secret irgendeinen Platzhalter hat, kann das hinterher noch nach dem AuthReceived-Event geändert werden, und man muss nichts im Browser selber eingeben, aber das secret wird nicht im Client gespeichert, sondern kann beim Server bleiben, der auch den Code empfängt. 

(Bin gerade zu müde für Englisch :D )

**Comment by BrianLima** [comment]
So, in the end there's no secure way to use the Spotify API and be secure on a standalone desktop app? All the ways to store the secretId can be broken, specially for open source apps.

**Comment by h-philip** [comment]
If you don't want to have server-side code and keep ur secretId secret, I think the [Implicit Grant Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#implicit-grant-flow) is the best way.

**Comment by JohnnyCrazy** [comment]
Sadly this is not a complete secure solution either @h-philip . You would have to register localhost as a redirect URI, a this allows everyone to generate tokens since everyone "controls" this domain.

The only completely secure alternative, besides running a Backend Server, is to force the client to register a new developer app. This way, everyone has its own secret and client IDs. This also allows using authorization code auth for long lively tokens. However, spotify made it a real pain to generate new apps, so it's not very practical...

**Comment by BrianLima** [comment]
Thanks for the insight guys. I think i might drop the Spotify integration altogether for my project in the end and try to use a more broad Windows Media Playback API. It might even be more suited.

**Comment by StepIg** [comment]
@BrianLima
What are you talking about?

**Comment by rollersteaam** [comment]
@StepIg He's most likely just saying he'll use local files stored on the user's computer as part of the music in his project instead, although I'm just making guesses since AFAIK Windows Media Playback can only do that.

@JohnnyCrazy First off, I just wanted to thank you for creating this library and all the time you've put into it. You brought my project to life and it's very unlikely I would have got this far without your help. Thank you. I think my project is near release but it's closed source (but free), do you only showcase open source projects on your documentation page?

And for my second question, do you have examples of this backend server that would do the key exchange? I'm not sure what the process of the key exchange is, but after thinking about this for a while I might be open to the idea of trying to roll my own php script that I'll probably just hoist on github pages, but only if I could understand the basics of what the php would be returning. Not saying do the entire thing for me (unless you're open to the challenge obviously) but I would be **very** grateful for a few pointers if you know of some.

**Comment by BrianLima** [comment]
@rollersteaam you are right, but that will not solve the problem anyway.

**Comment by rollersteaam** [comment]
After 11 hours straight working on a solution to my own problem of refreshing authentication without re-opening the browser, securing the client secret and figuring out what 'performing a key change' on a 'backend' server actually meant, I have finally reached the end. The golden pot at the end of the rainbow.

I managed to hack enough of @JohnnyCrazy 's new 3.0.0 AuthorizationCodeAuth class to obtain user permissions initially by opening the browser, but by defining my own redirect URI that links to an auth folder on my website, I can redirect the start.html via meta tag refresh to my start.php, where I construct a GET request to the Spotify API. The GET request has the redirect URI that I link to it in start.php, so when it returns the authentication code it links to a safe, whitelisted page hosted on my website. Then I construct a meta refresh tag on that page with php and send along the authentication code to http://localhost:4002 via redirect, where SpotifyAPI's local server is still listening to the owls and crickets.

I didn't provide a unique state parameter however, that was just 123 for now, may add that along the request pipeline eventually as its kind of important security wise... And for scopes, I didn't pass those along either. I debugged Scope.GetStringAttributes(" ") on program init and copied the string representation of the scopes I had already previously defined in the object constructor of AuthorizationCodeAuth, and pasted them into the authorize GET request to Spotify. Hacky, but what the hell isn't hacky about any of this solution?

But the big goal was getting it TO the localhost:4002. This opened up the big iron door blocking the way: getting from "browsing" web browser pages back to my application with the auth code from Spotify intact. Now the authentication received event was fired, I can begin to prepare phase 2, the handshake. Using HTTPClient I make a post request with the response code to, again, a php file hosted on my website which uses curl and inits to the spotify token api. The magic of it is in the server-side only execution, the **client secret** is defined as a constant, but only to my server. So I can construct the header requirements with the base64 encode perfectly with no user involvement whatsoever. Then I just add the normal auth code to the post body and send it along. When the result is returned, the HTTPClient automatically receives the message and parses it from json to the Token object already provided by SpotifyAPI Models. Boom. That. Is. It. I've got my access token. I've got my refresh token. I've got my 1 hour long expire times. I've got my client secret locked away and out of sight. And the process is completely seamless. Now getting there and setting it up **was NOT seamless**, but for the user its like any other day.

Now don't get me wrong. I'm sure there is MUCH MORE efficient ways to do this, but it's 7am, I haven't slept, and I've worked for 11 hours straight learning php for the first time and learning the avalanche of cheesecake that http requests are, but I will post code tomorrow when I actually sleep because I'm dying as I type this.

Main goals now are finding out how to halt execution of my program while waiting for the AuthReceived event to fire and setting up an automatic refresh authentication system/timer which I think I **know** how to refresh without use of the browser opening. After that I have completely finished my integration with Spotify and have all issues clear from my plate. Tomorrow's sounding pretty good to me.

**Comment by rollersteaam** [comment]
@JohnnyCrazy @BrianLima I've created a gist with everything you need to know about php files, html files and usage of AuthorizationCodeAuth to obtain a 'full' flow of secure authentication for the Spotify API.

https://gist.github.com/rollersteaam/26bf07f99f9ef768a1c71c4f61fb66a4

It's worth noting you CANNOT use GitHub Pages to host your php files, you must get a free or paid web server that supports php scripts to do it, otherwise all of your php code will not only not work, but display as normal HTML and expose what you set your CLIENT_SECRET to.

This can be made a lot better probably? It's possible we can also made changes to SpotifyAPI-NET to also better support this use case based off of what I've had to do here, although I haven't thought that deeply into it.

The only thing missing is getting a refreshed access token. It will follow a similar process to what is already shown, and I'll likely release the code for that when I've done it. But **everything** shown in that gist will get you your valuable access token and using the API right away - it's just that I didn't code the 'refresh' way. I'll update my gist and put a post here when I get around to it.

**Comment by rollersteaam** [comment]
I'm on a roll, [I've updated the git, here's the link to it again,](https://gist.github.com/rollersteaam/26bf07f99f9ef768a1c71c4f61fb66a4) and this time I've added refresh_token to index.php and therefore the ability to request refreshed access tokens using your php server. I've also implemented a timer that will automatically refresh the current access token **silently**, meaning that no browser will be opened up on refresh. That means that the only time in the whole process the browser is opened up is on program init.

That's my wild journey into php and HTTP request garbage OVER. Hopefully I do not have to touch these topics of programming again for maybe a year or so. This took me basically 15 hours to do in total. Consider this my payback for creating a lovely API :)

**Comment by rollersteaam** [comment]
[I've updated the gist again...](https://gist.github.com/rollersteaam/26bf07f99f9ef768a1c71c4f61fb66a4) This time I changed the code to block execution until authentication is received or it times out after 10 seconds of waiting. Very useful if you're expecting authentication to be gained right after calling that function. What should be improved about it is marking ResolveAuth as async and returning a Task, as well as encompassing the function body with ANOTHER Task so that people can choose to await the task or let it run in the background. But damn, this has come a long damn way. I've solved all the problems that I've had with the SpotifyAPI-NET, and now there is the safe auth method that everyone can use readily available now. @JohnnyCrazy Do you think you could take a look at the gist and decide on whether you want to add it to your wiki or not? And if so, would you consider making a class that would suit this use case?

**Comment by rollersteaam** [comment]
I've completed the new authorization method. [I've created a pull request](https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/286) detailing the additions, the new classes are called SecureAuthorizationCodeAuth and SecureWebAPIFactory. SecureWebAPIFactory follows in the same footprint as the WebAPIFactory in 2.0.0, it's really easy to use with some very useful new features such as auto refreshing, access expiry events and auth success and failure events. SecureAuthorizationCodeAuth itself has silent refreshing for its access.

Creating your own exchange server is incredibly easy as well, it's quite literally just 2 php files into your php web server, input your necessary client id, secret, redirect uri, etc. in all the different files and you're good to go. You now have secured your client secret, you never need to open the user's browser to refresh access, and you can get your access automatically refreshed.

**Comment by OmiCron07** [comment]
@rollersteaam I'm trying to use your pull request and there is a little error with HtmlResponse. In SecureWebAPIFactory, the property HtmlResponse is never initialized to "", so when later on you check for HtmlResponse != "", you overwrite the default HtmlResponse with null. By the way, you should use string.IsNullOrEmpty method instead of a comparison with "".

**Comment by rollersteaam** [comment]
> @rollersteaam I'm trying to use your pull request and there is a little error with HtmlResponse. In SecureWebAPIFactory, the property HtmlResponse is never initialized to "", so when later on you check for HtmlResponse != "", you overwrite the default HtmlResponse with null. By the way, you should use string.IsNullOrEmpty method instead of a comparison with "".

@OmiCron07  Oh god that's bad, didn't realise strings were nullable. Thanks for the assist, was trying to rapidly implement a feature in my app so had to change my fork haphazardly, would have never picked up on that since I change html response. Hope your implementation using the fork is going well, if you ever need help I updated the wiki entry for authorization on my fork which details the process quite a bit.

**Comment by OmiCron07** [comment]
@rollersteaam Yeah, found the nice documentation and for now, is working great.

**Comment by JohnnyCrazy** [comment]
Sorry, Yes, will follow in some hours 😀

**Comment by ceriwestcott** [comment]
@JohnnyCrazy Nice! Thank you :+1:

**Comment by JohnnyCrazy** [comment]
@ceriwestcott 3.1.1 is rolled out and should be on NuGet soon, thanks for the heads-up :)
