### ISSUE TITLE
HTTP Error 404. The requested resource is not found.[Make HTTP-Server port variable]

### ISSUE THREAD

**Issue by Ray1235** [JohnnyCrazy/SpotifyAPI-NET#32]
Happens whenever I try to use the local server for SpotifyWebAPI ImplicitGrantAuth. Haven't tried the other ones yet, might be an issue on my side, but not sure.
Also, this happens with the example app too.

**Comment by JohnnyCrazy** [comment]
Hi,
got any applications running on port 80? Like XAMPP or any other HTTP-Service?
Sadly I have to run the server on port 80, no other choice here...

**Comment by Ray1235** [comment]
Why is it needed to run it on port 80?

**Comment by JohnnyCrazy** [comment]
Last time I checked, you could add e.g `localhost:8000` to your Apps redirect-uris. But as soon as you authed your application, it said `INVALID_REDIRECTURI`

**But**, it seems like it's possible now. I will push an option to change the port shortly. Maybe this will help resolving your isse :+1:

**Comment by JohnnyCrazy** [comment]
I just added variable ports in d8e3238f09ce02c76071f2365951822282596255
The example app is now using port 8000, could you try running it again? @Ray1235

**Comment by Ray1235** [comment]
Example app works now, thanks a lot :)

**Comment by freezepro** [comment]
Looks like old one, however I put your sample under some desktops(not development environment) and sometimes(and at some machines) it crashes showing 404 exception(when doing redirect form Spotify url to localhost:8000 or shows timeout exception. 

any troubleshooting ideas? I think we tried to use several different ports but no luck.

ps. one more question, is there quick way to wrap sportify sign-in window into WebViewer control rather than showing a separate browser window. I managed to do it in Electron/NodeJS version of spotify client, but now need .net one

**Comment by freezepro** [comment]
Looks like resolved, added my own app in spotify dev account and added other port.8000 is kinda too common

**Comment by maithao2206** [comment]
👍

**Comment by mrw95** [comment]
my xampp server is get error http error 404.the request resource is not found how to soled it
