### ISSUE TITLE
Automatically refresh access token

### ISSUE THREAD

**Issue by tomupson** [JohnnyCrazy/SpotifyAPI-NET#323]
Hi,

Is there a way to automatically request a new access token using the refresh token when it has expired and if not, is there a way for me to detect when the access token is no longer valid and request a new one myself? I have an application which will be running for long periods of time (certainly more than 1 hour), so requesting new access tokens is definitely important

Thanks

**Comment by JohnnyCrazy** [comment]
You can use the following method on the token object:

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/f173e23e1a8cd43e5660fbc11a4aa3fe0182b93e/SpotifyAPI.Web/Models/Token.cs#L37

If want to refresh before the token is expired, you'll have to manually compare the `CreateDate` of the token with the current time.

Then use `RefreshToken(string refreshToken)` of `AuthorizationCodeAuth`:

https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/f173e23e1a8cd43e5660fbc11a4aa3fe0182b93e/SpotifyAPI.Web.Auth/AuthorizationCodeAuth.cs#L49

**Comment by JohnnyCrazy** [comment]
Addition: There is currently no automatic refresh implemented, library users should implement this on their own because it can be achieved in various ways (Threading Timer, Blocking Timer etc.) and not everyone wants to use the same way.

Feel free to re-open the issue if you have additional questions
