### ISSUE TITLE
TrackResource is null when ad is running

### ISSUE THREAD

**Issue by eltoncezar** [JohnnyCrazy/SpotifyAPI-NET#34]
When an ad starts playing, the `TrackResource` in **SpotifyLocalAPI.cs** line **98** is null, thus crashing the application.

Also, in the previous version, there was the `IsAdRunning()` method. There's something similar in this version? or how can I check if there's an ad running?

Thanks!

**Comment by JohnnyCrazy** [comment]
Thanks!
I will propably fix it in the next days.

Regarding AD-Detection:  
It was using the `PlayEnabled`, `PrevEnabled` and `NextEnabled` properties. While it worked most of the time, there were some issues: Sometimes you start up spotify and end up with an empty queue. This empty queue made all mentioned properties `false` and the API would detect it as an AD. Thats why I removed it. But, since you mentioned the empty `TrackResource`, maybe we could rely on that to detect it?

**Comment by JimmyAppelt** [comment]
I was tying to detect it with the Tracktype (When playing an ad it will return the string "ad")

status.Track.TrackType

But no success yet

**Comment by JimmyAppelt** [comment]
Hi,

Indeed the app crashes when an ad is playing.

The TrackType in the Track object will return the string "ad" - when an add is playing

**Comment by JohnnyCrazy** [comment]
This is fixed in d1f1923738ea48e9e74549fccb083e6037d03682

Also, you can now check if a Track is an Advert by running:
````csharp
track.IsAd()
````

**Comment by JimmyAppelt** [comment]
Great work Johnny will run some tests on this :facepunch:
