### ISSUE TITLE
Paging and sorting for SearchItems

### ISSUE THREAD

**Issue by ColorTwist** [JohnnyCrazy/SpotifyAPI-NET#398]
I am using  `SearchItems `to search artists by name by country,
In some cases I know I have more than 50 results, but I am not sure how to use the paging with `SearchItems `and sort it by popularity using `offset` with the `HasNextPage() `logics.
```

 Paging<FullArtist> item = api.SearchItems("Larry", SearchType.Artist, 50, 0, "ES").Artists ;

   do
            {
                item.Items.ForEach(artist =>
                {
                    i++;
                    Console.WriteLine($"- {i} {artist.Name} {artist.Popularity}");
                });
                item = await api.GetNextPageAsync(item);
            } while (item.HasNextPage());
```

**Comment by JohnnyCrazy** [comment]
Hi @ColorTwist 

Yea, paging with search can be difficult. The problem is basically that the `Paging<FullArtist>` object is always embedded inside of a `SearchItem` object. Thus, even if you get the next page of artists, it will be delivered as a `SearchItem`.

However, you can specify the correct type when using `GetNextPageAsync` like this:

```csharp
private static async Task ProcessAllLarrys(SpotifyWebAPI api)
{
    int i = 0;
    var initial = await api.SearchItemsAsync("Larry", SearchType.Artist, 50, 0, "ES");
    await ProcessSomeLarrys(api, initial);
}

private static async Task ProcessSomeLarrys(SpotifyWebAPI api, SearchItem searchResult, int i = 0)
{
    if (searchResult.Artists != null)
    {
        searchResult.Artists.Items.ForEach(artist => Console.WriteLine($"- {++i} {artist.Name} {artist.Popularity}"));
        if (searchResult.Artists.HasNextPage())
            await ProcessSomeLarrys(api, await api.GetNextPageAsync<SearchItem, FullArtist>(searchResult.Artists), i);
            # Automatically cast the result to a SearchItem
    }
}
```

Also, note that your code does not handle the last page. It will stop the while loop before writing it to console. (I think I saw this somewhere in the example of this repo, gonna update it)
