### ISSUE TITLE
Can i login 2 account in one application ?

### ISSUE THREAD

**Issue by imxike** [JohnnyCrazy/SpotifyAPI-NET#429]
Hi @JohnnyCrazy , I'm trying to make an winform app where user can sync there spotify playlists between their accounts. How can i login 2 or more accounts from your lib ?
 
And thanks for your work, its make me very easier to work with the api :D

**Comment by henriquenunez** [comment]
There are two different things: The client authorization (within Spotify's server), and the user authorization. You need to create one instance of the `SpotifyWebAPI` for each user, and with the needed authorization provided, you can interact properly.
If you want to expand this, I'd recommend creating an `IEnumerable<SpotifyWebAPI>` such as a `Dictionary` so you can have a more general approach (any number of accounts).

**Comment by JohnnyCrazy** [comment]
Like @henriquenunez said, create multiple instances of `SpotifyWebAPI`. You can also create them on the fly and store the access_token in some kind of database.

Authentication is tricky tho, since you need to login with 2 different accounts and brwosers tend to save your session into cookies. Maybe have to use incognito or logout manually.
