### ISSUE TITLE
v6: If fields are explicitly specified on Playlist.GetItems, it fails with "Received unkown [sic] playlist element type: "

### ISSUE THREAD

**Issue by palenshus** [JohnnyCrazy/SpotifyAPI-NET#472]
For example:

```csharp
var playlistGetItemsRequest = new PlaylistGetItemsRequest();
playlistGetItemsRequest.Fields.Add("items(track(name,preview_url,artists(name)))");
playlistGetItemsRequest.Fields.Add("limit");
playlistGetItemsRequest.Fields.Add("next");
playlistGetItemsRequest.Fields.Add("offset");
playlistGetItemsRequest.Fields.Add("total");
var playlistItems = await this.spotify.Playlists.GetItems(playlistId, playlistGetItemsRequest);
```

I'm guessing that the SDK assumes there will be some field present in the response and throws up if it can't find it. This worked in the v5 API (and via the Spotify web console), so I'd expect the v6 to be able to handle it too.

**Comment by palenshus** [comment]
Ah, looking at the code, it looks like it needs the items(track(type)) property specified, tricky. I guess I'd either document that explicitly, or add that field internally in the SDK

**Comment by JohnnyCrazy** [comment]
Yea, since we don't have any type information available, we're unable to cast the field to the correct model.

I think manually adding the field is too much behind the scenes. I adapted the exception message to include some more details and documented it on the [IPlayableItem](https://johnnycrazy.github.io/SpotifyAPI-NET/docs/next/iplayableitem) page.

Thanks for the heads-up! :)

**Comment by palenshus** [comment]
Nice, thank you!
