### ISSUE TITLE
Refreshing tokens on app restart

### ISSUE THREAD

**Issue by michaelfoster9** [JohnnyCrazy/SpotifyAPI-NET#510]
I'm sorry if this isn't the best place for asking questions, as this isn't a bug report.

I am currently using the Authorization Code method for a desktop application.  It works great.  When my app starts up, I send a web browser to "https://accounts.spotify.com/authorize/?client_+id......".    I then get a code back which i can use to exchange for a token.

When the user shuts down my app and restarts it, the authorize url above doesn't make the user login again. It redirects me to the Redirection URL and gives me the auth code, which is great. My users don't need to login each time they run the app.  However, this doesn't work when users Authenticate with Facebook. When that happens, I get an "Invalid-grant" error when I try to use the code that is sent to my redirection page.

so my questions are:
* Do I need to do anything different for Facebook? I wouldn't think so
* Is the PKCE flow better for desktop and mobile applications anyways?
* When I tried PKCE it does seem to work better, however the user has to accept the Scopes each time I restart the application which is a little annoying. Is that normal?

thanks for your help. My app was working great until facebook users started complaining so I'm wondering if I'm doing something wrong here.

thanks for the help with this great library.

**Comment by JohnnyCrazy** [comment]
Hi,

> I am currently using the Authorization Code method for a desktop application. It works great. When my app starts up, I send a web browser to "accounts.spotify.com/authorize/?client_+id......". I then get a code back which i can use to exchange for a token.

If you're using `Authorization Code`, you don't even need to redirect your users every time. You just have to do it once, since in the response you will get an `access_token` and a `refresh_token`. If the `access_token` is expired, you can get a new one by making a hidden POST request with `refresh_token`. There is no user action needed after the first authentication.

> When the user shuts down my app and restarts it, the authorize url above doesn't make the user login again. It redirects me to the Redirection URL and gives me the auth code, which is great. My users don't need to login each time they run the app. However, this doesn't work when users Authenticate with Facebook. When that happens, I get an "Invalid-grant" error when I try to use the code that is sent to my redirection page.

AFAIK there is no difference with facebook users, never heard of any problems specific to facebook users either. I'm guessing there is something happening while opening the browser, maybe a malformed login URI.

> Do I need to do anything different for Facebook? I wouldn't think so

No, spotify OAuth2 does not behave differently when the user has a facebook account.

> Is the PKCE flow better for desktop and mobile applications anyways?

Yes, definitely! You don't need to expose your `client_secret` and is [suggested by spotify](https://developer.spotify.com/community/news/2020/06/18/pkce-oauth/)

You can also have a look at the [persistent CLI example app](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web.Examples/Example.CLI.PersistentConfig/Program.cs), it even stores the tokens so it has to be authenticated only once! :) 

> When I tried PKCE it does seem to work better, however the user has to accept the Scopes each time I restart the application which is a little annoying. Is that normal?

No, but this is happening because you open the browser each time your app starts. Like I said before, do it once, persist it somewhere and then use the persisted tokens to make calls and if they expire, refresh them (without user interaction!)
