### ISSUE TITLE
favicon.ico on CustomHTML

### ISSUE THREAD

**Issue by JackDjTom** [JohnnyCrazy/SpotifyAPI-NET#565]
Hi, you have an example project for using CustomHTML...

I implemented that aswell and it works great!
But I wondered if there's a way to also show a favicon.ico (Tab-Icon). I tried couple of things but nothing worked :/

`<link rel="icon" href="./favicon.ico">` in the header of index.html didn't work when the favicon.ico was in the same directory as the index.html.

Since index.html is a _Embedded Resource_ in the VS project, i tried to set favicon.ico also as Embedded Resource but that did also nothing.

Can you tell me how to use a favicon for the CustomHTML example?

**Comment by JohnnyCrazy** [comment]
Hi

Just tested this with the example CLI, putting a `favicon.ico` in the resources folder and `<link rel="icon" href="./favicon.ico">` in the HTML.

If you immediately stop the server after you receive the authentication result, it will not work since favicon fetching is delayed by the browser. I added a `Task.Delay(TimeSpan.FromSeconds(5))` at the start of `OnAuthorizationCodeReceived` and it displayed the icon correctly.

Could you check that out?

**Comment by JackDjTom** [comment]
Thanks for the quick answer!

Sadly that doesn't work for me :/
Did everything as you said.

`await Task.Delay(TimeSpan.FromSeconds(5));` at the start of `OnAuthorizationCodeReceived `
`<link rel="icon" href="./favicon.ico">` in the `head`-element of the HTML
`favicon.ico` in the resource folder (I tried in Resource and in Resource/custom_page)

I'm using Chrome and an adblocker, maybe there's the problem...

But displaying the favicon works fine if I use a link from the internet like that:
`<link rel="icon" href="https://i.imgur.com/2rfJs74.png"/>`

I'll probably use a link then.

But I appreciate you're help man, you're awesome, keep it up :D

**Comment by JohnnyCrazy** [comment]
Tested it with 3 different browser, not sure what could be the problem here. But yes, using a link is a good workaround!
