### ISSUE TITLE
NUnit Tests, are they worth the effort?

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#7]
Guess it would be a good idea to have some tests.
Although most methods then need to be redone (Include checking for valid parameters).

**Comment by JohnnyCrazy** [comment]
So with the rewrite, I added some example unit tests [here](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Tests/TestClass.cs#L48)

I still not know if it's a good idea or just a waste of time. Most of the methods just exist out of string-building.

**Comment by Mrnikbobjeff** [comment]
They definitely are worth the effort, as some bugs can be caught early. One recommendation I would have is to refactor your source to automatically initialise Paging.Items objects, as this would enable other people to use the given data containers without additional effort. Furthermore I would recommend to change the if clauses in which you check whether a string is empty (market != "" e.g.) with String.IsNullOrEmpty, as it is a recommended practice for libraries according to Microsoft Basic Desgin Guideline Rules. Anyhow, keep up the great work with this project!

**Comment by JohnnyCrazy** [comment]
@Mrnikbobjeff 

But is it worth writing about 3-4 unit-tests for each API-Call, which *maybe* catches simple bugs? With about 40 API-Calls implemented, that would be around 120-160 Tests, thats a lot to write :sweat_smile:

**Comment by Mrnikbobjeff** [comment]
It is an investment in the future. An excellent book concerning this and many other topics which are relevant for programming is Andrew Hunt's "The Pragmatic Programmer". There he encourages the use of Contracts and Unit tests for every independent module. Most tests can simply be copied if they test similar results (e.g. GetAlbumArt and GetAlbumArtAsync would not need separate tests). He describes tests as methods which prevent "time bombs" from being implemented in the code. 
Generally speaking I find them to be worth the effort. In one of my last paid projects I designed a school management system with server integration, mobile app integration and asp.net web service. The entire project contained approximately 120k lines of code, of which a solid 25k were tests and documentation. The tests were only added after I had to rewrite a central piece of software which was used throughout the different modules. After this enormous task a colleague recommended that  I read the aforementioned book. It really taught me fundamental rules and approaches to many problems I faced. Since then I strictly apply most guidelines which were mentioned in the book, which really took a burden of my shoulders. If your local library has a copy of this book I would recommend that you read it.
