### ISSUE TITLE
Retry-After Header Lookup

### ISSUE THREAD

**Issue by S3NS4Ti0N** [JohnnyCrazy/SpotifyAPI-NET#82]
Would be nice to check the time given in the "Retry-After" handler, to not overload the Spotify API.

It would be clever to have that in the "SpotifyAPI.Web.Models.Error" as Property or as a Property in an "SpotifyAPI.Web.SpotifyWebAPI" instance

For reference please check this : https://developer.spotify.com/web-api/user-guide/#rate-limiting

**Comment by JohnnyCrazy** [comment]
Sounds like a good idea, will have a look at it tomorrow! :+1:

**Comment by erinxocon** [comment]
I was thinking the same thing the other day!

**Comment by JohnnyCrazy** [comment]
Turns out this won't be as easy as I thought.

My idea was adding a `HeaderCollection` to the `BasicModel` which will be automatically filled once the client got the response-headers. To achieve this, we would need to add `where T : BasicModel` to all the Download-Methods so the Method can set the `HeaderCollection` appropriately. This works for 90% of the API-Calls, but sadly we also have those _weird_ array API-Calls `CheckSavedTracks` `CheckSavedAlbums` etc.. Their response can either be a `JArray` or an Error-Object (`BasicModel`). I couldn't find a solution for creating a class for this kind of responses which will deserialize correctly **and** suits  `T DownloadData<T> where T : BasicModel`.

So, you guys got any ideas for a clean implementation or a workaround for my approach?

I couldn't find a solution

**Comment by S3NS4Ti0N** [comment]
I think it will be totally okay if we have the headers only on the Error-Object. In my opinion you don't have to look at the headers when everything is okay.

**Comment by JohnnyCrazy** [comment]
I just pushed an implementation to the `headers` branch. Every Model now contains a `ResponseInfo Response`-property, which currently only holds `WebHeaderCollection Headers` but may contain more in the future.

Usage:
```
FullAlbum album = _spotify.GetAlbum("1KFttYHEjNkDMYQrV6qYMA");

//'Response' is marked as JsonIgnore
//Will contain response headers
album.Response.Headers 
```

I'm not quite happy with it, but I can't think of a nicer solution currently. I plan to move to `HttpClient` in the near future, then this hopefully will get a makeover.

Thoughts? @S3NS4Ti0N @erinxocon @JimmyAppelt

**Comment by JohnnyCrazy** [comment]
Implemented in 15d8fd87e22a9e0ae4a9a5f0071152eefcf6d384

**Comment by petrroll** [comment]
Just out of curiosity what's the point of WebHeaderCollection? I can see it being passed around but not really used anywhere...

**Comment by JohnnyCrazy** [comment]
@petrroll 
Rate limit detection. If your exceeding the rate limit, a header will be set by the web api and users can detect it via that header collection

**Comment by pentiumii400mhz** [comment]
I can't get the Header to work, can you please add a example, the Header and the Headers Collection is allways empty? One problem is also that when Header("Retry-After") is "Nothing" I get a exception if I don't check if the Headers Collection is Nothing. Can this be more simple?

I really would like to have a simple way of getting how long time I should wait befor retrying agin?

**Comment by JohnnyCrazy** [comment]
@pentiumii400mhz 

Can't reproduce it, headers are working fine:
![img](http://i.imgur.com/OX8sjjA.png)

`Header(string name)` will return `null` if there is no header with that name, so there should be everything you need for a `Retry-After`-check

**Comment by pentiumii400mhz** [comment]
Hi

I'm sorry but when I'm getting a Error 429 the headers is Empty!

![image](https://cloud.githubusercontent.com/assets/21958884/18243371/2029d278-735b-11e6-9b0b-37b4f38e52ca.png)

![image](https://cloud.githubusercontent.com/assets/21958884/18243377/27fa88f8-735b-11e6-80a2-9f6d089b2404.png)

![image](https://cloud.githubusercontent.com/assets/21958884/18243387/2d1ae544-735b-11e6-968e-cfdd33fbfc3b.png)

**Comment by pentiumii400mhz** [comment]
Anyone?

**Comment by JohnnyCrazy** [comment]
I will have a look at this the next days, kinda got out of my sight
