### ISSUE TITLE
Local api cannot connect to spotify

### ISSUE THREAD

**Issue by Vampie** [JohnnyCrazy/SpotifyAPI-NET#86]
Hi,

Last year I tried to create a simple app to control my local spotify.
That worked thanks to your api.

Now I upgraded your api and the spotify client, but the app won't connect to the local player anymore.

    _localSpotify = new SpotifyLocalAPI();
    while (!_localSpotify.Connect())
    {
        Application.DoEvents();
    }
    MessageBox.Show("locally connected");
    
And I never see the messagebox appearing.
It just hangs.......

I tried the examples that come with the api and I have the same problem.

Anything I can do or any recent changes (on the spotify client perhaps) that could have broken it?

Thanks.

//edit: local spotify version : 1.0.29.90.g200ff544

**Comment by Vampie** [comment]
UPDATE: 

I tried the same code at home and it works.

So it is probably the spotify client.
At home I have version 1.0.21.143.g76c19bcd

**Comment by JohnnyCrazy** [comment]
Hi @Vampie ,

The Spotify local API is often very bitchy. Sometimes it's the antivirus which blocks the local Spotify API Server and sometimes it's the api itself which does't work at all. Often you just have to restart the WebHelper and the Spotify client a lot until it works. Sadly Spotify doesn't support the API in any way, that's why we can't expect a lot...

Can you try restarting it and maybe check if you have a different anti-virus software or something ( #51 )?

**Comment by Vampie** [comment]
Strange. Friday evening it worked on both machines.
Haven't tried it in the weekend and now it does not work on the first machine it did not work on.

I'll keep trying/monitoring what happens.

tnx.
