### ISSUE TITLE
Direction for use for Web applications

### ISSUE THREAD

**Issue by adaam2** [JohnnyCrazy/SpotifyAPI-NET#87]
I would really like to use this library and implement the OAuth flow in an MVC application. The current docs for OAuth flow using this library are based on the assumption that you will be using WinForms to develop. Having taken a look at the source, the GetAuthUrl() method is set to private and the Sample project is wholly WinForms. Considering I already have a web server setup (IIS) to receive the response from the Spotify OAuth redirect back to the development site, is there any documentation on using this library this way?

Cheers,

Adam

**Comment by JohnnyCrazy** [comment]
Hi,

The whole Authentication-implementation is very hacky and was, like you said, just designed for WinForms usage. It seems like you can implement some kind of OWIN OAuth2 Strategy fairly easy in ASP.NET MVC 5, however, I don't have much experience with ASP.NET. 

But since you said you already have an OAuth Redirect, which auth-flow are you using?

**Comment by adaam2** [comment]
Okay thanks, I'll have a look at this - I already have a client library for Twitter implementing the standard server access token flow so I'll see if I have enough time to play around with the SpotifyAPI-NET source code and so that it is easier to make use of this library in web applications.

I'll get back to you with a PR if I get round to it!

Thanks

A
