### ISSUE TITLE
can not use any other spotify account when running Example.ASP

### ISSUE THREAD

**Issue by SujalGupta910** [JohnnyCrazy/SpotifyAPI-NET#879]
When i try to run the Example.ASP project on my local machine, with my clientid and clientsecret, i can authenticate with my spotify account and see my playlists as expected. However, when i try to authenticate with someone else's spotify account and my clientid and clientsecret as previous, i get an internal server error on my browser:

HttpRequestException: An error occurred while retrieving the user profile.

AspNet.Security.OAuth.Spotify.SpotifyAuthenticationHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)
Exception: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync() 

I would like to know if there is a way to fix this, or if this is how the project was meant to work.  Thank you

**Comment by JohnnyCrazy** [comment]
Hi,

This could be because you need to allow-list if your registered app is still in development mode. You can find more info here: https://developer.spotify.com/documentation/web-api/concepts/quota-modes

The spotify account, which created the app, is automatically allow-listed. This might explain what you're seeing.

if that's not the case, feel free to re-open
