### ISSUE TITLE
.NET Framework support

### ISSUE THREAD

**Issue by Hi-ImKyle** [JohnnyCrazy/SpotifyAPI-NET#893]
![image](https://github.com/JohnnyCrazy/SpotifyAPI-NET/assets/25551312/17d32d14-1275-4b15-a306-5cfbf57bca24)
.NET Framework doesn't actually look like its supported. Any chance it will or is it a remnant of what you did support but dropped for X reasons?

Tried installing the library through nuget but there are no builds targeting .NET Framework according to nuget.

**Comment by JohnnyCrazy** [comment]
Which exact Version of .NET framework are you targeting?

**Comment by Hi-ImKyle** [comment]
4.8

**Comment by Hi-ImKyle** [comment]
I can go all the way to 6.2.2 for SpotifyAPI but anything past that, nuget throws up a warning that it doesn't offer a .NET Framework compatible build

**Comment by JohnnyCrazy** [comment]
Mh, true, I think Support got dropped when we removed Support for net Standard 2.0.

We do use some language + framework Features only available in Standard 2.1, but we used some Compiler flags back then to disable them for 2.0.

Let me investigate a bit what it would take to get Support for that back.

**Comment by Hi-ImKyle** [comment]
Also does no one offer a local API anymore? I'll be honest, the only reason I'm using this library is because it's the only maintained one. I just want the currently playing track/position. Seems overkill to have a Web API endpoint just for that when the currently playing song is always playing locally... I don't like the idea of sending a currently playing song request every second or less just to get the track position..

**Comment by WXRIW** [comment]
> Also does no one offer a local API anymore? I'll be honest, the only reason I'm using this library is because it's the only maintained one. I just want the currently playing track/position. Seems overkill to have a Web API endpoint just for that when the currently playing song is always playing locally... I don't like the idea of sending a currently playing song request every second or less just to get the track position..

You can use GSMTC (Windows 10 1809 or above required) to get the session info, but sadly there are some drawbacks.
1. The session does not contain Spotify ID and ISRC.
2. Spotify has weak support on GSMTC, so it's not working properly every time, a restart for Spotify might be needed if it's not working.
My app Lyricify is using GSMTC (Media Session) for playback status enhancement, since Current Playback API are returning 429 error very often.

**Comment by Inzaniity** [comment]
I just want to chime in that I also would like to upgrade to the latest version on my .net framework application. Sadly it's too much effort to port to .net standard/core or whatever naming MS now uses.

**Comment by JohnnyCrazy** [comment]
Just released 7.0.2, which re-adds support for .net standard 2.0. This will allow it to be used in the following [.NET Framework versions](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0):

> 4.6.1 2, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 4.8.1

Some functionalities, like `PaginateAll`, are not available due to missing support.

Let me know if that works out for everyone 👍🏼
