### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [JohnnyCrazy/SpotifyAPI-NET#906]
Maybe You will be interested in hosting API Explorer online:

https://www.robiniadocs.com/d/spotifyapi-net/api/SpotifyAPI.Web.html
This is ready-to-go, so above link can be added to README for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/spotifyapi-net/api/SpotifyAPI.Web.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/spotifyapi-net/api/SpotifyAPI.Web.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by JohnnyCrazy** [comment]
Hey,

That's a cool project, I like how easy it is to get onboarded! 
For this project however, I would rather host the API docs on something like GitHub pages. Simply because I would like dependencies to other providers to be minimal. This reduces the possibility of stuff breaking or being offline.

I will investigate how we can integrate the API docs into the existing docs at https://johnnycrazy.github.io/SpotifyAPI-NET/
