### ISSUE TITLE
Continue playing playlist after PlayUrl

### ISSUE THREAD

**Issue by vivaldinho** [JohnnyCrazy/SpotifyAPI-NET#96]
Hello
Scenario:
I'm listening a playlist/album/radio on the player.
I send a new uri with PlayUrl.
The song plays, the song ends, and the player stops. :-s
Anyones knows how to do the player continues playing the songs on the same playlist/album/radio after play the uri sent byt PlayUrl?
Thanks in advance

**Comment by vivaldinho** [comment]
Is the project died or my question is stupid?

**Comment by jholzer** [comment]
Please think about your workflow:
- You are playing some playlist
- Then you trigger a new song by sending an URL to Spotify-player
- The song ends.

The player has no idea what to do next. 
So what should it play?

Please not that the library is no player by itself, but (besides the Webservice wrapper) a "remote-control" for the Spotify-Player. As long as Spotify does not implement some "What-to-do-after-playback-ends"-behavior the player will stop. And i think they won´t since it makes no sense...

Btw,; That is a behavor i would expect from any player. 
Imagine you have a CD-player, Windows Media Player, VCR. 
You insert a CD, MP3, etc. and play it. 
What happens when it´s done?

What you CAN do: 
Monitor the status of the player´s playback (can be done with this library) and implement some behavior in you application. (if playback status changes to "stop", the play something)
Then you e.g. could send the URL of some other track or (i think that´s what you want, or at leaast what get´s closest to that) a Spotify-playlist.

Hope this helps!

**Comment by vivaldinho** [comment]
Thanks for your reply. Then, must be my question was stupid :-)
Or not...
In previous versions of Spotify, the workflow was:

- You are playing the song  Song1 from a playlist containing Song1, song2, song3.
- You send a new song to Spotify.
- This song starts to play and ends.
- Spotify continues playing Song2, the next song in the playlist.
After i do not remember wich version, the behavious was changed.

In other way, when i ask for the shuffle state, i receive allways a False value. Can you help with this?

Thanks for all and best regards
ViV

**Comment by jholzer** [comment]
As far as i´ve observed, "Shuffle" works within a (let´s say) collection. This may be a playlist, an album, library or similar. (Maybe i´m wrong with that, so playes correct me in case)
But as soon you send a single track to be played then this track will be the only content of Spotify player´s playback collection. So there´s nothing left to play.

But again: the library cannot influence the deeper behavior patterns of Spotify player except of playing an URL and stopping it. And it cannot change it. The only instance that can do that is Spotify.
(Some silly example: If Spotify developers decide to play the sound of a crying baby after each song you will have no chance chaning that...)

But feel free to play around by sending URLs of track, playlists, etc... and oberve how Spotify behaves.
If you find any knowledge about that behavor: please share with the community!

**Comment by vivaldinho** [comment]
There must be something wrong anywhere...
I start your SpotifyAPI.Example, i start playing a playlist on Spotify and the shuffle is all time false ¿?
Can you check this or may be only works bad for me?

**Comment by JohnnyCrazy** [comment]
Seems like spotify removed support for getting shuffle and repeat status, it's always false currently.

And like @jholzer said, spotify behaves differently. If you double click a song, it will be directly played and the context in which you click it will be used for the future queue. Imagine double clicking a track inside a playlist. Then the playlist will continue after the song ended. Same for albums. You are looking for `AddToQueue` which sadly doesn't work anymore, see #24
